import {
  Search,
  X,
  AlertTriangle,
  Lock,
  Wallet,
  CreditCard,
  Shield,
  PartyPopper,
  Gift,
  Briefcase,
  Building2,
  TrendingUp,
  Film,
  Pill,
  FileText,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  Plus,
  Minus,
  Check,
  Trash2,
  Edit3,
  Copy,
  Eye,
  EyeOff,
  Menu,
  MoreVertical,
  PlusCircle,
  MinusCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Settings,
  Home,
  BarChart3,
  Calendar,
  Users,
  User,
  Camera,
  Image,
  Clock,
  Bell,
  Mail,
  Phone,
  MapPin,
  Globe,
  CalendarDays,
  Star,
  Heart,
  Folder,
  File,
  FilePlus,
  FolderPlus,
  Link2,
  ExternalLink,
  LogOut,
  LogIn,
  UserPlus,
  UserCheck,
  ShieldCheck,
  LockKeyhole,
  Key,
  RefreshCw,
  RefreshCcw,
  Loader2,
  Activity,
  AlertCircle,
  Info,
  HelpCircle,
  XCircle,
  CheckCircle,
  AlertOctagon,
  TriangleAlert,
  Ban,
  Filter,
  SlidersHorizontal,
  SortAsc,
  SortDesc,
  Maximize2,
  Minimize2,
  ZoomIn,
  ZoomOut,
  Move,
  GripVertical,
  MoreHorizontal,
  Circle,
  Square,
  Hexagon,
  Octagon,
  Triangle,
  Diamond,
  Crosshair,
  Target,
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  BatteryCharging,
  Power,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Video,
  VideoOff,
  Monitor,
  Smartphone,
  Tablet,
  Watch,
  Printer,
  Headphones,
  Speaker,
  Music,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Repeat,
  Shuffle,
  List,
  Grid,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Type,
  Hash,
  AtSign,
  Send,
  MessageSquare,
  MessageCircle,
  Link,
  Clipboard,
  ClipboardList,
  CalendarPlus,
  CalendarCheck,
  Inbox,
  Archive,
  FolderOpen,
  Trash,
  Save,
  Share2,
  Share,
  PiggyBank,
  Sparkles,
} from 'lucide-react-native'

export {
  Search,
  X,
  AlertTriangle,
  Lock,
  Wallet,
  CreditCard,
  Shield,
  PartyPopper,
  Gift,
  Briefcase,
  Building2,
  TrendingUp,
  Film,
  Pill,
  FileText,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  Plus,
  Minus,
  Check,
  Trash2,
  Edit3,
  Copy,
  Eye,
  EyeOff,
  Menu,
  MoreVertical,
  PlusCircle,
  MinusCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Settings,
  Home,
  BarChart3,
  Calendar,
  Users,
  User,
  Camera,
  Image,
  Clock,
  Bell,
  Mail,
  Phone,
  MapPin,
  Globe,
  CalendarDays,
  Star,
  Heart,
  Folder,
  File,
  FilePlus,
  FolderPlus,
  Link2,
  ExternalLink,
  LogOut,
  LogIn,
  UserPlus,
  UserCheck,
  ShieldCheck,
  LockKeyhole,
  Key,
  RefreshCw,
  RefreshCcw,
  Loader2,
  Activity,
  AlertCircle,
  Info,
  HelpCircle,
  XCircle,
  CheckCircle,
  AlertOctagon,
  TriangleAlert,
  Ban,
  Filter,
  SlidersHorizontal,
  SortAsc,
  SortDesc,
  Maximize2,
  Minimize2,
  ZoomIn,
  ZoomOut,
  Move,
  GripVertical,
  MoreHorizontal,
  Circle,
  Square,
  Hexagon,
  Octagon,
  Triangle,
  Diamond,
  Crosshair,
  Target,
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  BatteryCharging,
  Power,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Video,
  VideoOff,
  Monitor,
  Smartphone,
  Tablet,
  Watch,
  Printer,
  Headphones,
  Speaker,
  Music,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Repeat,
  Shuffle,
  List,
  Grid,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Type,
  Hash,
  AtSign,
  Send,
  MessageSquare,
  MessageCircle,
  Link,
  Clipboard,
  ClipboardList,
  CalendarPlus,
  CalendarCheck,
  Inbox,
  Archive,
  FolderOpen,
  Trash,
  Save,
  Share2,
  Share,
  PiggyBank,
  Sparkles,
}

export const ICON_MAP = {
  search: Search,
  x: X,
  'alert-triangle': AlertTriangle,
  lock: Lock,
  wallet: Wallet,
  'credit-card': CreditCard,
  shield: Shield,
  party: PartyPopper,
  gift: Gift,
  briefcase: Briefcase,
  building: Building2,
  'trending-up': TrendingUp,
  film: Film,
  pill: Pill,
  'file-text': FileText,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  plus: Plus,
  minus: Minus,
  check: Check,
  trash: Trash2,
  edit: Edit3,
  copy: Copy,
  eye: Eye,
  'eye-off': EyeOff,
  menu: Menu,
  'more-vertical': MoreVertical,
  'plus-circle': PlusCircle,
  'minus-circle': MinusCircle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  settings: Settings,
  home: Home,
  chart: BarChart3,
  calendar: Calendar,
  users: Users,
  user: User,
  camera: Camera,
  image: Image,
  clock: Clock,
  bell: Bell,
  mail: Mail,
  phone: Phone,
  'map-pin': MapPin,
  globe: Globe,
  star: Star,
  heart: Heart,
  folder: Folder,
  file: File,
  'file-plus': FilePlus,
  'folder-plus': FolderPlus,
  'link-2': Link2,
  'external-link': ExternalLink,
  'log-out': LogOut,
  'log-in': LogIn,
  'user-plus': UserPlus,
  'user-check': UserCheck,
  'shield-check': ShieldCheck,
  'lock-keyhole': LockKeyhole,
  key: Key,
  'refresh-cw': RefreshCw,
  'refresh-ccw': RefreshCcw,
  loader: Loader2,
  activity: Activity,
  'alert-circle': AlertCircle,
  info: Info,
  'help-circle': HelpCircle,
  'x-circle': XCircle,
  'check-circle': CheckCircle,
  'alert-octagon': AlertOctagon,
  warning: TriangleAlert,
  ban: Ban,
  filter: Filter,
  sliders: SlidersHorizontal,
  'sort-asc': SortAsc,
  'sort-desc': SortDesc,
  maximize: Maximize2,
  minimize: Minimize2,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  move: Move,
  grip: GripVertical,
  'more-horizontal': MoreHorizontal,
  wifi: Wifi,
  'wifi-off': WifiOff,
  bluetooth: Bluetooth,
  battery: Battery,
  'battery-charging': BatteryCharging,
  power: Power,
  volume: Volume2,
  'volume-x': VolumeX,
  mic: Mic,
  'mic-off': MicOff,
  video: Video,
  'video-off': VideoOff,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  watch: Watch,
  printer: Printer,
  headphones: Headphones,
  speaker: Speaker,
  music: Music,
  play: Play,
  pause: Pause,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  rewind: Rewind,
  'fast-forward': FastForward,
  repeat: Repeat,
  shuffle: Shuffle,
  list: List,
  grid: Grid,
  'piggy-bank': PiggyBank,
  sparkles: Sparkles,
} as const

export type IconName = keyof typeof ICON_MAP